fantasy: Die.hpp Combat.hpp Creature.hpp Goblin.hpp Barbarian.hpp ReptilePeople.hpp BlueMen.hpp TheShadow.hpp menu.hpp
	g++ main.cpp Die.cpp Combat.cpp Creature.cpp Goblin.cpp Barbarian.cpp ReptilePeople.cpp BlueMen.cpp TheShadow.cpp menu.cpp -o game
clean:
	rm -f *o game