game: Shadow.hpp BlueMen.hpp Reptile.hpp Barbarian.hpp Goblin.hpp Creature.hpp Combat.hpp Die.hpp menu.hpp Stack.hpp Queue.hpp
	g++ main.cpp Shadow.cpp BlueMen.cpp Reptile.cpp Barbarian.cpp Goblin.cpp Creature.cpp Combat.cpp Die.cpp menu.cpp Stack.cpp Queue.cpp -o play
clean:
	rm -f *o play
